version: '3'
services:
  backend:
    build: ./backend
    volumes:
      - pocketbase_data:/pb/pb_data
    ports:
      - "8090:8080"
    restart: unless-stopped

  web:
    build: ./web
    ports:
      - "3000:3000"
    environment:
      # PUBLIC_PB_URL: URL for the PocketBase instance
      # If not set in the environment, defaults to http://backend:8080
      # This allows for flexibility in production
      - PUBLIC_PB_URL=${PUBLIC_PB_URL:-http://backend:8080}
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  pocketbase_data: