version: "3"
services:
  backend:
    build: ./backend
    volumes:
      - pocketbase_data:/pb/pb_data
    ports:
      - "8090:8080"
    restart: unless-stopped

  web:
    build: ./web
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  pocketbase_data:
